name = "japanese-chicken-curry"
kind = "recipe"

[ingredients]
chicken = 1
potato = 1
carrot = 3
ginger = 0.5
garlic = { quantity = 1, optional = true }
curry-cubes = 1
cornstarch = "1 tbsp"
soy-sauce = { quantity = "1 tbsp", optional = true }

