name = "kung-pao-chicken"
kind = "recipe"

[ingredients]
chicken = 2
red-bellpepper = 2
green-bellpepper = 2
soy-sauce = "1 tbsp"
cornstarch = "1 tbsp"
peanuts = { quantity = "1 handful", optional = true }
