# fly.toml app configuration file generated for inven on 2023-07-29T16:10:40-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "inven"
primary_region = "sjc"

[env]
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
